### ISSUE TITLE
RPM_Measure.ino fails (floating point arithmetic within ISR)

### ISSUE THREAD

**Issue by tshcherban** [khoih-prog/ESP32TimerInterrupt#10]
Hi
i'm getting an error while running your example:
`Guru Meditation Error: Core  1 panic'ed (Coprocessor exception)`
if change calculation from float to integers - works good.
Also found this thread [Floating point in ISR?](https://www.esp32.com/viewtopic.php?t=831), which warns about using floats within interrupt handlers on ESP32.

**Comment by khoih-prog** [comment]
Hi @tshcherban 

Thanks for the info. 
Even though I haven't got that error `Guru Meditation Error: Core 1 panic'ed (Coprocessor exception)`, I'll put a note and  change the `float` to `int` in the example for next release.
