### ISSUE TITLE
Setting a timer number when the default contructor is used.

### ISSUE THREAD

**Issue by aramperez** [khoih-prog/ESP32TimerInterrupt#13]
### Is your feature request related to a problem? Please describe.

I'm using v1.2.0. I'd like to use an ESP32TimerInterrupt (ESP32Timer) object inside a class without having to use a pointer.

I don't understand  why there is a default constructor "ESP32TimerInterrupt()"  that sets the timer number (_timerNo) to MAX_ESP32_NUM_TIMERS but there is no setTimer() method. There is a "getTimer()" method that returns the private _timerNo variable.

### Describe the solution you'd like

Add a setTimer(uint8_t timerNo) method.

### Describe alternatives you've considered
My current solution is to have a pointer variable to an ESP32TimerInterrupt and allocate it either in my object constructor or other method.

**Comment by khoih-prog** [comment]
Thanks for your interest and enhancement request.

The reason I wrote the library like that is to force users decide and choose the Hardware Timer well before using it. As you know, **using ISR Timer is a serious business**, and can't be treated arbitrarily.

**It's dangerous to permit user to switch the Timer on-the-fly**, using setTimer(uint8_t timerNo), in the middle of something, which can create a disaster.

The default constructor is there **redundant**, can can be deleted in the future. if I think it's not necessary and dangerous.


You can create a pointer, then initialize when necessary as follows:

```
ESP32Timer *ITimer0;

void setup()
{
  Serial.begin(115200);
  while (!Serial);
  ...

  // Interval in microsecs

  ITimer0 = new ESP32Timer(0);
  if (ITimer0->attachInterruptInterval(TIMER1_INTERVAL_MS * 1000, TimerHandler0))
  {
    Serial.print(F("Starting  ITimer0 OK, millis() = ")); Serial.println(millis());
  }
  else
    Serial.println(F("Can't set ITimer0. Select another freq. or timer"));
}
```

Good Luck,
