### ISSUE TITLE
Panic core on Esp33

### ISSUE THREAD

**Issue by guimaraesjm** [khoih-prog/ESP32TimerInterrupt#19]
### Describe the bug

O have used this code to make measure rpm of 4 systems and always esp32 dev kit v4 came the error of panic core!
Do you have any solution?

I’m using vscode with plataformio with arduino lib.

**Comment by khoih-prog** [comment]
Hi,

I suggest next time you have to post a more detailed `issue` to save us time to look around and investigate a vague issue. Following the requirements in [**Issue: Bug report**](https://github.com/khoih-prog/ESP32TimerInterrupt/issues/new?assignees=&labels=&template=bug_report.md&title=)

**I almost close the issue** before I search and found out your post on [**Facebook**](https://www.facebook.com/groups/1606743019578078/) mentioning about the example [**RPM_Measure**](https://github.com/khoih-prog/ESP32TimerInterrupt/tree/master/examples/RPM_Measure)

This is actually a new issue for ESP32 core v2.0.0 and v2.0.1 as mentioned in [**ESP32 Core v2.0.1 / 2.0.1 RC1 crashes if using pinMode with GPIO1** #5868](https://github.com/espressif/arduino-esp32/issues/5868)

Just use the old core v1.0.6 or modify the code [RPM_Measure.ino#L78-L80](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/RPM_Measure/RPM_Measure.ino#L78-L80) to

```
#define PIN_D1              1         // Pin D1 mapped to pin GPIO1 of ESP32-S2
#define PIN_D2              2         // Pin D2 mapped to pin GPIO2/ADC12/TOUCH2/LED_BUILTIN of ESP32
#define PIN_D3              3         // Pin D3 mapped to pin GPIO3/RX0 of ESP32

unsigned int SWPin = PIN_D3;
```

from 

```
#define PIN_D1              1         // Pin D1 mapped to pin GPIO1 of ESP32-S2

unsigned int SWPin = PIN_D1;
```

Good Luck,
