### ISSUE TITLE
Disable

### ISSUE THREAD

**Issue by i17brn** [khoih-prog/ESP32TimerInterrupt#2]
How can I disable the timer? I am using timer 0 to sample a sensor, I have set up 1000 samplers per second (1 kHz) and will sample for about 4 seconds to get 4k values. after that, how can I disable timer 0?

**Comment by khoih-prog** [comment]
@i17brn 

It's helpful to go through all the examples to be familiar with all the major features of the library. For example [TimerInterruptTest](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/TimerInterruptTest/TimerInterruptTest.ino)

1. [To stop ITimer(0)](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/TimerInterruptTest/TimerInterruptTest.ino#L157)

```
ITimer0.stopTimer();
```

2. [To restart ITimer(0)](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/TimerInterruptTest/TimerInterruptTest.ino#L152)

```
ITimer0.restartTimer();
```
