### ISSUE TITLE
my esp32 is not working

### ISSUE THREAD

**Issue by ebineser** [khoih-prog/ESP32TimerInterrupt#20]
In the esp32 inbuilt led is on when i am connecting the esp32 module on my laptop, but it doesn't show in port in Arduino IDE software. But when i am pressing the enable pin or boot pin it show ports after  when i leave my hand from this doesn't work. sometimes its show then i upload mean it gone. i dont know why , anyone tell me the reason for this and how it solved..  

After some time when i press and hold the enable after parallely click on the boot button it set when i uploading i hold press on boot button it downloading but after  completing it doesn't do anything..

**Comment by khoih-prog** [comment]
HI,

Thanks for your interest in the library.
I'm also sorry to say that your general issue has nothing to do with the library, and I suggest to post the `request for help` on either [**Arduino**](https://forum.arduino.cc/c/using-arduino/installation-troubleshooting/18) or [**ESP32**](https://www.esp32.com/viewforum.php?f=19) forum where many experienced experts can help you out.

Good Luck,
