### ISSUE TITLE
ESP32TimerInterrupt.hpp syntax errors

### ISSUE THREAD

**Issue by pidloop** [khoih-prog/ESP32TimerInterrupt#25]
Hello! I'm trying to build examples/Argument_None in version 2.0.1 but I get the following error:

```
ESP32TimerInterrupt/src/ESP32TimerInterrupt.hpp:107:22: error: "/*" within comment [-Werror=comment]
   TIMER_GROUP_0 = 0, /*!<Hw timer group 0
```

looking around in ESP32TimerInterrupt.hpp it certainly does look like the comments have been busted:

 ```
97 /*
 98   //ESP32 core v1.0.6, hw_timer_t defined in esp32/tools/sdk/include/driver/driver/timer.h:
 99 
100   #define TIMER_BASE_CLK   (APB_CLK_FREQ)  //Frequency of the clock on the input of the timer groups
101 
102 
103  //@brief Selects a Timer-Group out of 2 available groups
104 
105 typedef enum
106 {
107   TIMER_GROUP_0 = 0, /*!<Hw timer group 0
108   TIMER_GROUP_1 = 1, /*!<Hw timer group 1
109   TIMER_GROUP_MAX,
110 } timer_group_t;
111 
```

Any way to fix this? Thanks.

**Comment by pidloop** [comment]
Many thanks for taking the time to reply.

After further investigation, the problem was I had changed the IDE warnings level from Default to All. This caused the compiler flag `-Werror=all` to be added, as one can see in the original error message in the more specific form of `-Werror=comment`.

With all respect, may I suggest that if you want to effectively remove a chunk of code you surround it with 
```
#if 0
-- dead code --
#endif
```

instead of assuming nested comments will be ignored.

Again, I don't mean to be critical -- I greatly appreciate your outstanding library. Thank you.

**Comment by khoih-prog** [comment]
I'm also using **IDE warnings level == All**. So there is something else in your system, possibly **Windoze** related ???

Thanks anyway,
