### ISSUE TITLE
 Error in the value defined by TIMER0_INTERVAL_MS

### ISSUE THREAD

**Issue by pedrojvs** [khoih-prog/ESP32TimerInterrupt#28]
### Describe the bug

I have used the example Argument_None.ino to check the operation of the library with an ESP32_C3. With the 2.20 version of the library when I define a value of 1000 in TIMER0_INTERVAL_MS a real value of 2000 ms is obtained. With version 2.1.0 the operation is correct.

### Steps to Reproduce

I have used the example Argument_None.ino to check the operation of the library with an ESP32_C3.

### Expected behavior

It was expected to obtain a square wave with a half-period equal to 1000 ms and it has been obtained measured with an oscilloscope of 2000 ms.

Arduino IDE version: 2.0.1
esp32c3-api1-20210207
OS: Windows 11

**Comment by khoih-prog** [comment]
Hi @pedrojvs 

The new [**ESP32TimerInterrupt releases v2.3.0**](https://github.com/khoih-prog/ESP32TimerInterrupt/releases/tag/v2.3.0) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP32TimerInterrupt#contributions-and-thanks)

Best Regards,

---
### Releases v2.3.0

1. Fix doubled time for ESP32_C3, ESP32_S2 and ESP32_S3. Check [**Error in the value defined by TIMER0_INTERVAL_MS** #28](https://github.com/khoih-prog/ESP32TimerInterrupt/issues/28)
2. Modify examples to avoid using `LED_BUILTIN` / `GPIO2` as it cam cause crash in some boards, such as `ESP32_C3`
3. Use `allman astyle` and add `utils`
