### ISSUE TITLE
Start Timer

### ISSUE THREAD

**Issue by i17brn** [khoih-prog/ESP32TimerInterrupt#3]
How to start the timer on an event, I mean setting the timer parameters but not starting the counts. However, when an event occurs, such as a port interrupt, the timer starts counting

**Comment by khoih-prog** [comment]
I suggest you read my comment in your previous post, test then apply to your use case. The library just provides the basic functions and you have to understand the functions to apply them in your case. I certainly have no time to help you write your code.

Use the 

```
ITimer0.restartTimer();
```

> It's helpful to go through all the examples to be familiar with all the major features of the library. For example [TimerInterruptTest](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/TimerInterruptTest/TimerInterruptTest.ino)
> 
> 1. [To stop ITimer(0)](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/TimerInterruptTest/TimerInterruptTest.ino#L157)
> 
> ```
> ITimer0.stopTimer();
> ```
> 
> 2. [To restart ITimer(0)](https://github.com/khoih-prog/ESP32TimerInterrupt/blob/master/examples/TimerInterruptTest/TimerInterruptTest.ino#L152)
> 
> ```
> ITimer0.restartTimer();
> ```
