### ISSUE TITLE
a quick question

### ISSUE THREAD

**Issue by m-menon** [khoih-prog/ESP32TimerInterrupt#5]
hi, I am about to try something with this timer before that I thought I'd have a word with you; Do you think it will be fine to stop or restart the timer from within the timer callback? Just checking if there could be any known issues with that? And thanks for the excellent library. I have just started using it.

Couple of other simple questions. I am going through the examples as we speak but may be you could give me a pointer or two.

> They can also generate alarms when they reach a specific value, defined by the software.

Is the above accomplished by using the ISR Timer as shown below?

```
// Just to demonstrate, don't use too many ISR Timers if not absolutely necessary
ISR_Timer.setInterval(2000L, doingSomething2s);
```

If I want the timer to fire say 5 times, then I would declare a global variable and keep the count. Am I correct? Thanks.

**Comment by khoih-prog** [comment]
@m-menon 

Thanks for using the library and encouraging words.

It's difficult to know what you'd like to know and to achieve, I suggest to go through all the examples to understand all the complicated aspects of the Timer Interrupt, and use it correctly and effectively.

You can see you can stop/start the ISR timers as many times as you like, in the [**TimerInterruptTest example**](https://github.com/khoih-prog/ESP32TimerInterrupt/tree/master/examples/TimerInterruptTest).

Also have a look at some more complicated examples in [**SmallProjects**](https://github.com/khoih-prog/SmallProjects), for example [**FireSmokeAlarm**](https://github.com/khoih-prog/SmallProjects/tree/master/FireSmokeAlarm)

Have a good time exploring,

**Comment by m-menon** [comment]
@khoih-prog thanks for the links and the tips. I will explore the projects and see how it all goes. I'll close this now. Cheers.
