### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by fabltd** [khoih-prog/ESP32TimerInterrupt#9]
Hi 

Thanks for a great lib. I have been reading the documentation but feel its lacking clarification of the following:

What is the use of #include "ESP32TimerInterrupt.h" V #include "ESP32_ISR_Timer.h" ? Some examples have both but some only 1.

Some of the examples don't have an explanation of what they do? For some one new to this it is difficult to work out the missing bits.

Also can the time be specified in micro seconds? All examples show it in MS.

I note the following comments in the example:

// Using ESP32  => 80 / 160 / 240MHz CPU clock ,
// For 64-bit timer counter
// For 16-bit timer prescaler up to 1024

What does this mean and where is the value set?

Could you also suggest the best example to follow for this use case.

I have a 433 MHz radio receiver connected to an ESP32 pin. To decode the protocol I need to time how long the pin is high and low for after a preset high period (Sync bit). 

Thanks

**Comment by khoih-prog** [comment]
You can have a look at the [**TimerInterrupt Library**](https://github.com/khoih-prog/TimerInterrupt) which provide the similar features and functions.

1. [**Usage**](https://github.com/khoih-prog/TimerInterrupt#usage)
2. [**Set Hardware Timer Frequency and attach Timer Interrupt Handler function**](https://github.com/khoih-prog/TimerInterrupt#13-set-hardware-timer-frequency-and-attach-timer-interrupt-handler-function)
3. [**How to use attachInterruptInterval() parameters**](https://github.com/khoih-prog/TimerInterrupt/issues/11)

The perfect docs can be never achieved to satisfy everyone. The Interrupt-related library was written with the expectation that the users are experienced in hardware/firmware, and can read the public source code, examples to understand and apply / adapt into the real use-cases.

Good Luck with your interesting project,
